import { useEffect, useMemo, useRef, useSyncExternalStore } from "react";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import { getStats, refinerProgress, subscribeStats } from "./economy";
import { cellOffsets } from "./grid";
import { getLatest, subscribe } from "./store";

const MAX_REFINERS = 4096;
const BAR_Y = 1.48;
const TRACK_WIDTH = 0.66;
const TRACK_HEIGHT = 0.1;
const FILL_WIDTH = 0.58;
const FILL_HEIGHT = 0.045;
const FILL_LAYER = 0.003;

const ACTIVE_TRACK = new THREE.Color("#ffffff");
const IDLE_TRACK = new THREE.Color("#777c86");

function gradientTexture(): THREE.DataTexture {
  const stops = [
    { at: 0, color: new THREE.Color("#ef7f55") },
    { at: 0.58, color: new THREE.Color("#f6c453") },
    { at: 1, color: new THREE.Color("#fff0a8") },
  ];
  const width = 64;
  const data = new Uint8Array(width * 4);
  for (let i = 0; i < width; i++) {
    const t = i / (width - 1);
    const upper = stops.findIndex((stop) => stop.at >= t);
    const right = stops[Math.max(upper, 1)];
    const left = stops[Math.max(upper - 1, 0)];
    const span = right.at - left.at;
    const color = left.color.clone().lerp(right.color, span > 0 ? (t - left.at) / span : 0);
    data[i * 4] = Math.round(color.r * 255);
    data[i * 4 + 1] = Math.round(color.g * 255);
    data[i * 4 + 2] = Math.round(color.b * 255);
    data[i * 4 + 3] = 255;
  }
  const texture = new THREE.DataTexture(data, width, 1, THREE.RGBAFormat);
  // THREE.Color stores the parsed stop colours in the renderer's linear
  // working space, so the generated bytes are already linear too.
  texture.colorSpace = THREE.LinearSRGBColorSpace;
  texture.minFilter = THREE.LinearFilter;
  texture.magFilter = THREE.LinearFilter;
  texture.needsUpdate = true;
  return texture;
}

// RefinerProgress draws every status bar in two instanced WebGL meshes. The
// bars stay proportional to their machines at every zoom level without adding
// one DOM node and one animation callback per refiner in large factories.
export function RefinerProgress() {
  const track = useRef<THREE.InstancedMesh>(null!);
  const fill = useRef<THREE.InstancedMesh>(null!);
  const dummy = useMemo(() => new THREE.Object3D(), []);
  const right = useMemo(() => new THREE.Vector3(), []);
  const towardCamera = useMemo(() => new THREE.Vector3(), []);
  const fillTexture = useMemo(gradientTexture, []);
  const snap = useSyncExternalStore(subscribe, getLatest);
  const stats = useSyncExternalStore(subscribeStats, getStats);

  useEffect(() => () => fillTexture.dispose(), [fillTexture]);

  useFrame(({ camera }) => {
    if (!snap) {
      track.current.count = 0;
      fill.current.count = 0;
      return;
    }
    const { offX, offZ } = cellOffsets(snap);
    const count = Math.min(stats.refiners.length, MAX_REFINERS);
    const now = performance.now();
    right.set(1, 0, 0).applyQuaternion(camera.quaternion);
    towardCamera.set(0, 0, 1).applyQuaternion(camera.quaternion);

    for (let index = 0; index < count; index++) {
      const status = stats.refiners[index];
      const x = status.x - offX;
      const z = status.y - offZ;
      const active =
        !!status.resource ||
        status.queued > 0 ||
        (status.incoming ?? 0) > 0 ||
        (status.nextOutput ?? 0) > 0;

      dummy.position.set(x, BAR_Y, z);
      dummy.quaternion.copy(camera.quaternion);
      dummy.scale.set(1, 1, 1);
      dummy.updateMatrix();
      track.current.setMatrixAt(index, dummy.matrix);
      track.current.setColorAt(index, active ? ACTIVE_TRACK : IDLE_TRACK);

      const progress = refinerProgress(status, now);
      const leftOffset = ((progress - 1) * FILL_WIDTH) / 2;
      dummy.position
        .set(x, BAR_Y, z)
        .addScaledVector(right, leftOffset)
        .addScaledVector(towardCamera, FILL_LAYER);
      dummy.scale.set(progress, 1, 1);
      dummy.updateMatrix();
      fill.current.setMatrixAt(index, dummy.matrix);
    }

    track.current.count = count;
    track.current.instanceMatrix.needsUpdate = true;
    if (track.current.instanceColor) track.current.instanceColor.needsUpdate = true;
    fill.current.count = count;
    fill.current.instanceMatrix.needsUpdate = true;
  });

  if (!snap) return null;
  return (
    <>
      <instancedMesh ref={track} args={[undefined, undefined, MAX_REFINERS]} frustumCulled={false} raycast={() => null}>
        <planeGeometry args={[TRACK_WIDTH, TRACK_HEIGHT]} />
        <meshBasicMaterial
          color="#171b24"
          transparent
          opacity={0.88}
          depthTest={false}
          depthWrite={false}
          toneMapped={false}
        />
      </instancedMesh>
      <instancedMesh
        ref={fill}
        args={[undefined, undefined, MAX_REFINERS]}
        frustumCulled={false}
        raycast={() => null}
        renderOrder={1}
      >
        <planeGeometry args={[FILL_WIDTH, FILL_HEIGHT]} />
        <meshBasicMaterial
          map={fillTexture}
          transparent
          depthTest={false}
          depthWrite={false}
          toneMapped={false}
        />
      </instancedMesh>
    </>
  );
}
